---

- name: deitkrachten.facts
  src: https://github.com/de-it-krachten/ansible-role-facts.git
  version: main
  scm: git
- name: deitkrachten.package
  src: https://github.com/de-it-krachten/ansible-role-package.git
  version: main
  scm: git
