---

- name: Facts
  src: https://github.com/de-it-krachten/ansible-role-facts.git
  version: main
  scm: git

- name: Package
  src: https://github.com/de-it-krachten/ansible-role-package.git
  version: main
  scm: git
