---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    hashicorp_product: vagrant
  tasks:
    - name: Include role 'ansible-role-gnome_desktop'
      include_role:
        name: ansible-role-gnome_desktop
