---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    hashicorp_product: vagrant
  roles:
    - deitkrachten.showinfo
  tasks:
    - name: Include role 'ansible-role-gnome_desktop'
      ansible.builtin.include_role:
        name: ansible-role-gnome_desktop
